name: Ubuntu GUI with noVNC + Playit.gg (auto link)

on: [workflow_dispatch]

jobs:
  ubuntu-gui:
    runs-on: ubuntu-latest

    steps:
      - name: Cài GUI + noVNC + công cụ cần thiết
        run: |
          sudo apt update
          sudo apt install -y xfce4 xfce4-goodies tightvncserver websockify novnc curl gpg util-linux

      - name: Cấu hình VNC
        run: |
          mkdir -p ~/.vnc
          echo '123456' | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
          echo -e "#!/bin/bash\nstartxfce4 &" > ~/.vnc/xstartup
          chmod +x ~/.vnc/xstartup
          vncserver :1

      - name: Khởi động noVNC trên port 6080
        run: |
          websockify --web=/usr/share/novnc/ 6080 localhost:5901 &

      - name: Thêm APT repo & cài playit.gg
        run: |
          curl -SsL https://playit-cloud.github.io/ppa/key.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/playit.gpg >/dev/null
          echo "deb [signed-by=/etc/apt/trusted.gpg.d/playit.gpg] https://playit-cloud.github.io/ppa/data ./" | sudo tee /etc/apt/sources.list.d/playit-cloud.list
          sudo apt update
          sudo apt install -y playit

      - name: Chạy playit với terminal ảo (hiện link claim)
        run: |
          script -q -c "playit start" /dev/null

      - name: Giữ runner chạy 6 tiếng
        run: sleep 6h
