name: Ubuntu GUI with noVNC and Playit.gg

on: [workflow_dispatch]

jobs:
  ubuntu-gui:
    runs-on: ubuntu-latest

    steps:
      - name: Update & Install GUI + noVNC
        run: |
          sudo apt update
          sudo apt install -y xfce4 xfce4-goodies tightvncserver websockify novnc curl gpg

      - name: Setup VNC password & config
        run: |
          mkdir -p ~/.vnc
          echo '123456' | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
          echo -e "#!/bin/bash\nstartxfce4 &" > ~/.vnc/xstartup
          chmod +x ~/.vnc/xstartup
          vncserver :1

      - name: Start noVNC on port 6080
        run: |
          websockify --web=/usr/share/novnc/ 6080 localhost:5901 &

      - name: Add Playit APT repo & install
        run: |
          curl -SsL https://playit-cloud.github.io/ppa/key.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/playit.gpg >/dev/null
          echo "deb [signed-by=/etc/apt/trusted.gpg.d/playit.gpg] https://playit-cloud.github.io/ppa/data ./" | sudo tee /etc/apt/sources.list.d/playit-cloud.list
          sudo apt update
          sudo apt install -y playit

      - name: Start Playit tunnel
        run: |
          playit start

      - name: Keep session alive for 6h
        run: sleep 6h
