name: Ubuntu 20.04 GUI + noVNC + Playit

on:
  workflow_dispatch:

jobs:
  gui-on-ubuntu:
    runs-on: ubuntu-20.04

    steps:
    - name: Cài GUI, VNC, noVNC, tiện ích
      run: |
        sudo apt update && sudo apt install -y \
          xfce4 xfce4-goodies x11vnc novnc websockify \
          tightvncserver neofetch xterm curl gpg locales dbus-x11

    - name: Thiết lập locale và bỏ vùng/bàn phím
      run: |
        sudo locale-gen en_US.UTF-8
        echo 'LANG="en_US.UTF-8"' | sudo tee /etc/default/locale
        export LANG=en_US.UTF-8
        export LANGUAGE=en_US:en
        export LC_ALL=en_US.UTF-8

    - name: Cài Playit Tunnel
      run: |
        curl -SsL https://playit-cloud.github.io/ppa/key.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/playit.gpg >/dev/null
        echo "deb [signed-by=/etc/apt/trusted.gpg.d/playit.gpg] https://playit-cloud.github.io/ppa/data ./" | sudo tee /etc/apt/sources.list.d/playit-cloud.list
        sudo apt update && sudo apt install -y playit

    - name: Cấu hình VNC + XFCE
      run: |
        mkdir -p ~/.vnc
        echo -e "123456\n123456\nn" | vncpasswd
        cat > ~/.vnc/xstartup <<'EOF'
#!/bin/bash
xrdb $HOME/.Xresources
startxfce4 &
EOF
        chmod +x ~/.vnc/xstartup
        vncserver :1
        vncserver -kill :1

    - name: Khởi động GUI + VNC + noVNC
      run: |
        export DISPLAY=:1
        vncserver :1
        sleep 5
        x11vnc -display :1 -nopw -forever -bg
        websockify --web=/usr/share/novnc/ 8080 localhost:5901 &

    - name: Chạy Playit tunnel
      run: |
        playit start > playit.log &
        sleep 10
        echo "[+] Link từ Playit:"
        grep https playit.log || tail playit.log

    - name: Giữ cho workflow sống
      run: sleep 1080000
