name: Ubuntu 20.04 GUI + noVNC + Playit

on:
  workflow_dispatch:

jobs:
  ubuntu-gui:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Run Ubuntu 20.04 GUI in Docker
      run: |
        docker run -d --name ubuntu_gui -e DEBIAN_FRONTEND=noninteractive ubuntu:20.04 sleep infinity

        docker exec ubuntu_gui bash -c "\
          apt update && \
          apt install -y xfce4 xfce4-goodies x11vnc novnc websockify \
                         tightvncserver neofetch xterm curl gpg dbus-x11 locales && \
          curl -SsL https://playit-cloud.github.io/ppa/key.gpg | gpg --dearmor -o /usr/share/keyrings/playit.gpg && \
          echo 'deb [signed-by=/usr/share/keyrings/playit.gpg] https://playit-cloud.github.io/ppa/data ./' > /etc/apt/sources.list.d/playit-cloud.list && \
          apt update && apt install -y playit && \
          mkdir -p /root/.vnc && \
          echo -e '123456\n123456\nn' | vncpasswd && \
          echo '#!/bin/bash' > /root/.vnc/xstartup && \
          echo 'xrdb $HOME/.Xresources' >> /root/.vnc/xstartup && \
          echo 'startxfce4 &' >> /root/.vnc/xstartup && \
          chmod +x /root/.vnc/xstartup && \
          vncserver :1 && \
          vncserver -kill :1 && \
          export DISPLAY=:1 && \
          vncserver :1 && \
          x11vnc -display :1 -nopw -forever -bg && \
          websockify --web=/usr/share/novnc/ 8080 localhost:5901 & \
          playit start > /root/playit.log & \
          sleep 10 && \
          echo '[+] Link từ playit:' && \
          cat /root/playit.log | grep https || tail /root/playit.log \
        "

    - name: Keep Workflow Alive
      run: sleep 10800
