name: Ubuntu 20.04 GUI noVNC + Playit

on:
  workflow_dispatch:

jobs:
  run-gui:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Pull Ubuntu 20.04 + cài GUI
      run: |
        docker run --privileged -d --name gui-container ubuntu:20.04 sleep infinity

        docker exec gui-container bash -c "
          apt update && apt install -y \
            xfce4 xfce4-goodies x11vnc novnc websockify \
            tightvncserver neofetch xterm curl gpg git supervisor xorg openbox
        "

    - name: Cài Playit trong container
      run: |
        docker exec gui-container bash -c '
          curl -SsL https://playit-cloud.github.io/ppa/key.gpg | gpg --dearmor -o /usr/share/keyrings/playit.gpg &&
          echo "deb [signed-by=/usr/share/keyrings/playit.gpg] https://playit-cloud.github.io/ppa/data ./" > /etc/apt/sources.list.d/playit-cloud.list &&
          apt update && apt install -y playit
        '

    - name: Cấu hình VNC container
      run: |
        docker exec gui-container bash -c "
          mkdir -p /root/.vnc &&
          echo '123456' | vncpasswd -f > /root/.vnc/passwd &&
          chmod 600 /root/.vnc/passwd &&
          echo -e '#!/bin/bash\nstartxfce4 &' > /root/.vnc/xstartup &&
          chmod +x /root/.vnc/xstartup
        "

    - name: Chạy GUI + VNC + noVNC + Playit
      run: |
        docker exec -d gui-container bash -c "
          export DISPLAY=:1 &&
          vncserver :1 &&
          sleep 3 &&
          x11vnc -display :1 -nopw -forever -bg &&
          websockify --web=/usr/share/novnc/ 8080 localhost:5901 &
          playit start > /root/playit.log &
        "

    - name: In link từ Playit
      run: |
        sleep 10
        docker exec gui-container bash -c "cat /root/playit.log | grep https || tail /root/playit.log"

    - name: Giữ Workflow sống
      run: sleep 1080000
