name: GUI Ubuntu 20.04 + Playit (Docker)

on:
  workflow_dispatch:

jobs:
  gui-job:
    runs-on: ubuntu-latest

    steps:
    - name: Pull Ubuntu 20.04 & tạo container
      run: |
        docker pull ubuntu:20.04
        docker run -dit --name gui-container -e DEBIAN_FRONTEND=noninteractive ubuntu:20.04 bash

    - name: Cài GUI + Playit bên trong container (kèm locale + timezone)
      run: |
        docker exec gui-container bash -c "
          export DEBIAN_FRONTEND=noninteractive &&
          apt update &&
          apt install -y tzdata locales &&
          ln -fs /usr/share/zoneinfo/Asia/Ho_Chi_Minh /etc/localtime &&
          dpkg-reconfigure -f noninteractive tzdata &&
          locale-gen en_US.UTF-8 &&
          update-locale LANG=en_US.UTF-8 &&
          apt install -y xfce4 xfce4-goodies tightvncserver x11vnc novnc websockify \
                         curl gnupg2 xterm dbus-x11 lsb-release git

          mkdir -p /root/.vnc &&
          echo '123456' | vncpasswd -f > /root/.vnc/passwd &&
          chmod 600 /root/.vnc/passwd &&
          echo -e '#!/bin/bash\nstartxfce4 &' > /root/.vnc/xstartup &&
          chmod +x /root/.vnc/xstartup

          curl -SsL https://playit-cloud.github.io/ppa/key.gpg | gpg --dearmor -o /usr/share/keyrings/playit.gpg &&
          echo 'deb [signed-by=/usr/share/keyrings/playit.gpg] https://playit-cloud.github.io/ppa/data ./' > /etc/apt/sources.list.d/playit-cloud.list &&
          apt update && apt install -y playit
        "

    - name: Chạy GUI + VNC + noVNC + Playit
      run: |
        docker exec -d gui-container bash -c "
          export DISPLAY=:1 &&
          vncserver :1 &&
          x11vnc -display :1 -nopw -forever -bg &&
          websockify --web=/usr/share/novnc/ 8080 localhost:5901 &
          playit start > /root/playit.log 2>&1 &
        "

    - name: Đợi Playit tạo link
      run: sleep 15

    - name: In link từ Playit log
      run: |
        docker exec gui-container bash -c "
          grep https /root/playit.log || tail /root/playit.log
        "

    - name: Giữ cho workflow sống
      run: sleep 1080000
